version: '3'

services:
  app:
    build: .
    ports:
      - '8080:8080'
    container_name: app
    volumes:
      - ./migrations:/app/migrations
    depends_on:
      - db
      - jaeger

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=contact_bot_password
      - POSTGRES_DB=contact_book
    container_name: db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - '5775:5775/udp'
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
      - '16686:16686' # web
      - '14268:14268'
      - '9411:9411'